title: "BonusCollector"

baseurl: ""
url: "https://bonuscollector.de"

locale: de

markdown: kramdown

paginate: 12
paginate_path: "/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-paginate

collections:
  pages:
    output: true

permalink: pretty